name: E2E Tests

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/web/**'
      - '.github/workflows/e2e.yml'
  push:
    branches: [main]
    paths:
      - 'packages/web/**'
      - '.github/workflows/e2e.yml'
  # Manual trigger for testing
  workflow_dispatch:

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node-e2e-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-e2e-
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Install Playwright browsers
        run: |
          cd packages/web
          npx playwright install --with-deps chromium

      - name: Build application
        run: npm run build

      - name: Start application server
        run: |
          cd packages/web
          npm run preview &
          sleep 5
        env:
          CI: true

      - name: Wait for server to be ready
        run: |
          timeout 30 bash -c 'until curl -s http://localhost:4173 > /dev/null; do sleep 1; done'

      - name: Run E2E tests
        run: |
          cd packages/web
          npx playwright test --project=chromium
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: packages/web/playwright-report/
          retention-days: 7

      - name: Upload test videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-videos
          path: packages/web/test-results/
          retention-days: 7