[package]
name = "shogi_core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
matchbox_socket = { version = "0.12.0", features = ["ggrs"] }
ggrs = "0.11.1"
wasm-bindgen-futures = "0.4"
futures = "0.3"
log = "0.4"
wasm-logger = "0.2"
js-sys = "0.3.77"
gloo-timers = { version = "0.3.0", features = ["futures"] }
web-sys = { version = "0.3", features = ["CustomEvent", "CustomEventInit", "Window"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
