[package]
name = "shogi_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "convert_opening_book"
path = "src/bin/convert_opening_book.rs"

[[bin]]
name = "verify_opening_book"
path = "src/bin/verify_opening_book.rs"

[dependencies]
wasm-bindgen = "0.2"
matchbox_socket = { version = "0.12.0", features = ["ggrs"] }
ggrs = "0.11.1"
wasm-bindgen-futures = "0.4"
futures = "0.3"
log = "0.4"
wasm-logger = "0.2"
js-sys = "0.3.77"
gloo-timers = { version = "0.3.0", features = ["futures"] }
web-sys = { version = "0.3", features = [
    "CustomEvent", "CustomEventInit", "Window", "Location",
    "RtcPeerConnection", "RtcConfiguration", "RtcDataChannel", "RtcDataChannelEvent",
    "RtcPeerConnectionIceEvent", "RtcIceCandidate", "RtcSessionDescription",
    "RtcSessionDescriptionInit", "RtcSdpType", "RtcDataChannelState",
    "RtcIceConnectionState", "RtcSignalingState", "MessageEvent",
    "Performance"
] }
serde_json = "1.0"
base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
flate2 = "1.0"
rayon = "1.7"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
wasm-bindgen-futures = "0.4"

[dev-dependencies]
wasm-bindgen-test = "0.3"
