# Clippy configuration
# https://rust-lang.github.io/rust-clippy/

# Maximum cognitive complexity
cognitive-complexity-threshold = 30

# Maximum number of lines in a single function
too-many-lines-threshold = 100

# Maximum number of arguments in a function (default is 7)
too-many-arguments-threshold = 7

# Allow certain lints in tests
allow-dbg-in-tests = true

# Avoid breaking exported API
avoid-breaking-exported-api = false

# Allowed wildcard imports
allowed-wildcard-imports = []